#!/usr/bin/env node
import { existsSync } from "node:fs";
import { rm, mkdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import process from "node:process";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import type { Tool } from "@modelcontextprotocol/sdk/types.js";
import type { MessagesConfig } from "../src/config.js";
import { loadMessagesConfig } from "../src/config.js";

type CliOptions = {
  outputDir?: string;
  command?: string;
  args?: string[];
  filter?: string[];
};

const require = createRequire(import.meta.url);
const pkg = require("../package.json") as { name?: string; version?: string };

const MODULE_DIR = fileURLToPath(new URL(".", import.meta.url));
const PROJECT_ROOT = resolve(MODULE_DIR, "..");
const DEFAULT_OUTPUT_DIR = "src/agents/messages/generated";

function usage() {
  console.log(`Usage: pnpm ts-node --swc scripts/generate-mcp-wrappers.ts [options]\n\n` +
    `Options:\n` +
    `  --output <dir>    Override the output directory (default from config).\n` +
    `  --command <bin>   Command used to launch the MCP server (default: node).\n` +
    `  --arg <value>     Additional argument passed to the server (repeatable).\n` +
    `  --filter <names>  Comma-separated list of tool names to keep.\n` +
    `  -h, --help        Show this help message.\n`);
}

function parseCliArgs(argv: string[]): CliOptions {
  const options: CliOptions = {};
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--output") {
      options.outputDir = argv[i + 1];
      i += 1;
      continue;
    }
    if (arg === "--command") {
      options.command = argv[i + 1];
      i += 1;
      continue;
    }
    if (arg === "--arg") {
      const value = argv[i + 1];
      if (value) {
        if (!options.args) options.args = [];
        options.args.push(value);
      }
      i += 1;
      continue;
    }
    if (arg === "--filter") {
      const value = argv[i + 1];
      if (value) {
        options.filter = value.split(",").map((item) => item.trim()).filter(Boolean);
      }
      i += 1;
      continue;
    }
    if (arg === "--help" || arg === "-h") {
      usage();
      process.exit(0);
    }
  }
  return options;
}

function resolvePathWithinRepo(pathOrRelative: string): string {
  const resolved = resolve(PROJECT_ROOT, pathOrRelative);
  if (!resolved.startsWith(PROJECT_ROOT)) {
    throw new Error(`Refusing to write outside the repository: ${resolved}`);
  }
  return resolved;
}

function sanitizeToolLiteral(tool: Tool): string {
  const literal: Record<string, unknown> = {
    name: tool.name,
  };
  if (tool.description) {
    literal.description = tool.description;
  }
  if (tool.inputSchema) {
    literal.inputSchema = tool.inputSchema;
  }
  if (tool.metadata) {
    literal.metadata = tool.metadata;
  }
  const json = JSON.stringify(literal, null, 2);
  return json.replace(/"([a-zA-Z0-9_]+)":/g, (_match, key) => `${key}:`);
}

function splitSegments(value: string): string[] {
  return value
    .split(/[^a-zA-Z0-9]+/)
    .map((segment) => segment.trim())
    .filter(Boolean);
}

function toKebabCase(value: string): string {
  return splitSegments(value)
    .map((segment) => segment.toLowerCase())
    .join("-") || "tool";
}

function toPascalCase(value: string): string {
  const segments = splitSegments(value);
  if (segments.length === 0) return "Tool";
  return segments.map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1).toLowerCase()).join("");
}

async function ensureDir(path: string): Promise<void> {
  await mkdir(path, { recursive: true });
}

async function fetchTools(command: string, args: string[], env?: Record<string, string>): Promise<Tool[]> {
  const transport = new StdioClientTransport({
    command,
    args,
    cwd: PROJECT_ROOT,
    env,
    stderr: "inherit",
  });
  const client = new Client({
    name: "messages-wrapper-generator",
    version: pkg.version ?? "0.0.0",
  });
  try {
    await client.connect(transport);
    const response = await client.listTools({});
    return response.tools ?? [];
  } finally {
    await transport.close();
  }
}

async function writeToolModule(targetDir: string, tool: Tool): Promise<{ importName: string; callName: string; fileName: string }> {
  const pascalName = toPascalCase(tool.name);
  const importName = `${pascalName.charAt(0).toLowerCase()}${pascalName.slice(1)}Tool`;
  const callName = `call${pascalName}`;
  const fileName = `${toKebabCase(tool.name)}.ts`;
  const literal = sanitizeToolLiteral(tool);
  const contents = `// Auto-generated by scripts/generate-mcp-wrappers.ts. Do not edit.\nimport type { Client } from "@modelcontextprotocol/sdk/client/index.js";\nimport type { CallToolRequest, CallToolResult, Tool } from "@modelcontextprotocol/sdk/types.js";\n\nexport const ${importName}: Tool = ${literal} as const;\n\nexport type ${pascalName}Args = CallToolRequest["params"]["arguments"];\n\nexport async function ${callName}(client: Client, args: ${pascalName}Args = {}): Promise<CallToolResult> {\n  return client.callTool({\n    name: ${JSON.stringify(tool.name)},\n    arguments: args ?? {},\n  });\n}\n`;
  const filePath = join(targetDir, fileName);
  await writeFile(filePath, contents, "utf8");
  return { importName, callName, fileName };
}

async function writeIndexModule(targetDir: string, modules: Array<{ importName: string; fileName: string }>): Promise<void> {
  const relativeImports = modules
    .map(({ importName, fileName }) => `import { ${importName} } from "./tools/${fileName.replace(/\.ts$/, ".js" )}";`)
    .join("\n");
  const reExports = modules
    .map(({ fileName }) => `export * from "./tools/${fileName.replace(/\.ts$/, ".js")}";`)
    .join("\n");
  const toolList = modules
    .map(({ importName }) => `  ${importName},`)
    .join("\n");
  const contents = `// Auto-generated by scripts/generate-mcp-wrappers.ts. Do not edit.\nimport type { Tool } from "@modelcontextprotocol/sdk/types.js";\n${relativeImports}\n\nexport const messageTools = [\n${toolList}\n] satisfies Tool[];\n\nexport const messageToolMap = new Map(messageTools.map((tool) => [tool.name, tool] as const));\n\n${reExports}\n`;
  await writeFile(join(targetDir, "index.ts"), contents, "utf8");
}

async function generate(): Promise<void> {
  const cli = parseCliArgs(process.argv.slice(2));
  const config: MessagesConfig = await loadMessagesConfig();
  const wrapperConfig = config.codeExecWrappers ?? {};
  const outputDir = resolvePathWithinRepo(cli.outputDir ?? wrapperConfig.outputDir ?? DEFAULT_OUTPUT_DIR);
  const command = cli.command ?? wrapperConfig.serverCommand ?? process.execPath;
  const args = cli.args ?? wrapperConfig.serverArgs ?? ["dist/index.js", "--stdio"];
  if (!args || args.length === 0) {
    throw new Error("At least one server argument is required (path to dist/index.js)");
  }
  const serverArgs = [...args];
  if (serverArgs.length > 0) {
    const absoluteCandidate = resolve(PROJECT_ROOT, serverArgs[0]);
    if (existsSync(absoluteCandidate)) {
      serverArgs[0] = absoluteCandidate;
    } else if (!existsSync(serverArgs[0]) && /\.m?js$/i.test(serverArgs[0])) {
      throw new Error(`Unable to find ${serverArgs[0]}. Build the project or adjust --arg.`);
    }
  }
  const tools = await fetchTools(command, serverArgs, wrapperConfig.env);
  const filtered = cli.filter && cli.filter.length > 0
    ? tools.filter((tool) => cli.filter?.includes(tool.name))
    : tools;
  if (filtered.length === 0) {
    throw new Error("No tools returned by the MCP server.");
  }
  const sorted = filtered.sort((a, b) => a.name.localeCompare(b.name));
  const generatedRoot = outputDir;
  const toolsDir = join(generatedRoot, "tools");
  await rm(generatedRoot, { recursive: true, force: true });
  await ensureDir(toolsDir);
  const modules = [] as Array<{ importName: string; callName: string; fileName: string }>;
  for (const tool of sorted) {
    modules.push(await writeToolModule(toolsDir, tool));
  }
  await writeIndexModule(generatedRoot, modules);
  console.log(`Generated ${modules.length} tool wrappers in ${relative(PROJECT_ROOT, generatedRoot)}.`);
}

generate().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
