name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-doctor:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Run tests
        run: pnpm test

      - name: Doctor (diagnostics only)
        id: doctor
        run: |
          set -e
          pnpm run build
          pnpm run doctor:json > doctor-report.json || true
          echo "Doctor JSON written to doctor-report.json"
        env:
          NODE_ENV: test

      - name: Upload doctor report
        uses: actions/upload-artifact@v4
        with:
          name: doctor-report
          path: doctor-report.json
          if-no-files-found: warn
