name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: macos-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test --silent

      - name: Build
        run: npm run build --silent

      - name: Publish to npm
        if: env.NPM_TOKEN != ''
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public

      - name: Skip publish (missing NPM_TOKEN)
        if: env.NPM_TOKEN == ''
        run: echo "NPM_TOKEN not configured; skipping npm publish"
